### PR TITLE
Bug and typo fixes

### PR DESCRIPTION
**Pull request by robbyoconnor**
- Typos in README 
- Allow for features.serve_htdocs.php to not exist but still function and update the test to follow what the README says.

Includes fixes from #8 and #10

### CODE REVIEW

**Comment by robbyoconnor** [comment]
I re-opened it to trigger Travis CI

**Comment by robbyoconnor** [comment]
@gronke -- just pinging you <3

**Comment by gronke** [comment]
@robbyoconnor Thanks for the improvements and also for the little reminder :)

**Comment by robbyoconnor** [comment]
@gronke what's the point of this branch in the serve_htdocs feature template: https://github.com/gronke/ansible-nginx-site/blob/master/templates/features/serve_htdocs.j2#L13

**Comment by gronke** [comment]
It's not very common to serve raw .php files from a static webserver, but the risk of leaking configuration files is high if PHP was disabled by mistake. The location should be changed to not blacklist .bak files and log blocked file access attempts.

**Pull request merged**
