### PR TITLE
Add ability to use nginx ppa and add travis tests 

### PR DESCRIPTION
**Pull request by robbyoconnor**
This PR does two things (there was a dependency on #5 so I merged the two together:
- Adds the ability to use the official development PPA for nginx 
- Adds tests using docker and travis CI integration. Along the way, I fixed bugs that caused tests to fail. SSL is not tested due to...we need to figure out how to get a cert under CI....dhparams needs to be a rather small size...doesn't really matter as the containers are throwaways. 

The travis tests and the addition of the optional ability to use the PPA are in two commits.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
[Build Status](https://travis-ci.org/robbyoconnor/ansible-nginx-site)

I added the badge for your repo  in THE README -- linking here to show you it's all green-- which you need to enable :)

**Comment by robbyoconnor** [comment]
One improvement would be a way to run tests locally in docker...I'll do that separately -- or maybe as part of this one

**Comment by gronke** [comment]
Very nice! I have some tasks in my playbook that supports nginx Debian packages too that I will add to this role. Thank you, @robbyoconnor

**Comment by gronke** [comment]
A little follow-up: Debian support added with #7

**Pull request merged**
